# -*- coding: utf-8 -*-
"""
AlphaFold3 受体准备模块
功能：生成保留辅因子的受体 PDB，供给 AF3 调用
输出：results/[target_name]/AF3_receptor/af3-receptor.pdb
"""

import os
import sys
from pathlib import Path
from typing import List, Set, Dict

sys.path.insert(0, str(Path(__file__).parent))

from config import get_target_dirs


# 常见辅因子/配体残基名（保留在 AF3 受体中）
COFACTORS = {
    # 金属离子
    "ZN", "MG", "CA", "MN", "FE", "NA", "K", "CU", "CO", "NI",
    # ATP/ADP/AMP
    "ATP", "ADP", "AMP", "ANP",
    # NAD/NAP
    "NAD", "NAP", "NDP",
    # FAD
    "FAD", "FAA", "FAS",
    # 血红素
    "HEM", "HEC", "HEA", "HEB",
    # 其他辅因子
    "PLP", "PLM", "TDP", "TPP", "THP",
    "COA", "ACO", "ACP",
    "FMN", "MGD", "GTP", "GDP",
    # 常见离子
    "SO4", "PO4", "CL", "NA", "K",
    # 其他
    "BME", "DMS", "EDO", "GOL", "PEG",
}

# 标准氨基酸（三字母代码）
STANDARD_AA = {
    "ALA", "CYS", "ASP", "GLU", "PHE", "GLY", "HIS", "ILE", "LYS", "LEU",
    "MET", "ASN", "PRO", "GLN", "ARG", "SER", "THR", "VAL", "TRP", "TYR",
    # 常见变异
    "HID", "HIE", "HIP", "CYX", "CYM", "ASH", "GLH", "LYN", "ARN",
}


def identify_cofactors(pdb_file: Path) -> Dict[str, List[dict]]:
    """
    识别 PDB 中的辅因子和配体
    
    Returns:
        {残基名: [原子记录列表]}
    """
    cofactors = {}
    
    with open(pdb_file, 'r') as f:
        for line in f:
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                continue
            
            res_name = line[17:20].strip()
            
            # 跳过标准氨基酸（除非是水）
            if res_name in STANDARD_AA:
                continue
            
            # 识别为辅因子
            if res_name in COFACTORS or line.startswith("HETATM"):
                if res_name not in cofactors:
                    cofactors[res_name] = []
                
                cofactors[res_name].append({
                    "line": line,
                    "atom_name": line[12:16].strip(),
                    "chain_id": line[21].strip() if len(line) > 21 else "",
                    "res_seq": line[22:26].strip(),
                })
    
    return cofactors


def parse_cofactor_info(pdb_file: Path) -> List[Dict]:
    """
    解析辅因子详细信息
    
    Returns:
        辅因子列表，每个包含：
        - name: 残基名
        - chain: 链标识
        - seq: 残基序号
        - atom_count: 原子数
        - atoms: 原子列表
    """
    cofactor_dict = {}
    
    with open(pdb_file, 'r') as f:
        for line in f:
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                continue
            
            res_name = line[17:20].strip()
            
            # 跳过标准氨基酸和水
            if res_name in STANDARD_AA or res_name in ["HOH", "WAT", "H2O"]:
                continue
            
            chain_id = line[21].strip() if len(line) > 21 else ""
            res_seq = line[22:26].strip()
            
            key = (res_name, chain_id, res_seq)
            
            if key not in cofactor_dict:
                cofactor_dict[key] = {
                    "name": res_name,
                    "chain": chain_id,
                    "seq": res_seq,
                    "atoms": [],
                }
            
            cofactor_dict[key]["atoms"].append(line)
    
    # 转换为列表
    cofactors = []
    for key, data in cofactor_dict.items():
        data["atom_count"] = len(data["atoms"])
        cofactors.append(data)
    
    return cofactors


def create_af3_receptor(cleaned_pdb: Path, output_pdb: Path, 
                        keep_cofactors: bool = True,
                        cofactor_list: Set[str] = None):
    """
    创建 AF3 受体 PDB 文件
    
    AF3 需要：
    1. 完整的蛋白链
    2. 重要的辅因子（金属离子、ATP、NAD等）
    3. 去除水分子
    
    Args:
        cleaned_pdb: 清洗后的 PDB 文件
        output_pdb: 输出 PDB 文件
        keep_cofactors: 是否保留辅因子
        cofactor_list: 指定要保留的辅因子集合（None=保留所有识别的）
    """
    output_pdb.parent.mkdir(parents=True, exist_ok=True)
    
    # 统计信息
    stats = {
        "protein_atoms": 0,
        "cofactor_atoms": 0,
        "cofactor_types": set(),
    }
    
    with open(cleaned_pdb, 'r') as f_in, open(output_pdb, 'w') as f_out:
        f_out.write(f"REMARK   Generated by MCTS-Peptide Pipeline\n")
        f_out.write(f"REMARK   AF3 Receptor Preparation\n")
        f_out.write(f"REMARK   Source: {cleaned_pdb.name}\n")
        
        cofactors_found = []
        
        for line in f_in:
            # 保留 HEADER, TITLE, COMPND 等记录
            if line.startswith(("HEADER", "TITLE", "COMPND", "SOURCE", "KEYWDS", 
                               "EXPDTA", "AUTHOR", "REVDAT", "JRNL", "REMARK")):
                f_out.write(line)
                continue
            
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                if line.startswith(("TER", "END")):
                    f_out.write(line)
                continue
            
            res_name = line[17:20].strip()
            
            # 跳过水分子
            if res_name in ["HOH", "WAT", "H2O", "TIP", "TIP3"]:
                continue
            
            # 标准氨基酸：保留
            if res_name in STANDARD_AA:
                f_out.write(line)
                stats["protein_atoms"] += 1
                continue
            
            # 辅因子处理
            if keep_cofactors:
                # 如果指定了列表，只保留列表中的
                if cofactor_list and res_name not in cofactor_list:
                    continue
                
                # 保留 HETATM 记录（改为 ATOM 以兼容某些工具）
                modified_line = "ATOM  " + line[6:]
                f_out.write(modified_line)
                stats["cofactor_atoms"] += 1
                stats["cofactor_types"].add(res_name)
                
                if res_name not in cofactors_found:
                    cofactors_found.append(res_name)
        
        f_out.write("END\n")
    
    print(f"  蛋白原子: {stats['protein_atoms']}")
    print(f"  辅因子原子: {stats['cofactor_atoms']}")
    print(f"  辅因子类型: {', '.join(sorted(stats['cofactor_types'])) if stats['cofactor_types'] else '无'}")
    print(f"  ✓ AF3 受体: {output_pdb}")
    
    return stats


def prepare_af3_receptor(target_name: str, 
                         keep_cofactors: bool = True,
                         cofactor_filter: List[str] = None):
    """
    主入口：准备 AF3 受体文件
    
    Args:
        target_name: 靶点名称
        keep_cofactors: 是否保留辅因子
        cofactor_filter: 只保留指定的辅因子（如 ["ZN", "ATP"]）
    """
    print(f"\n{'='*60}")
    print(f"准备 AF3 受体: {target_name}")
    print(f"{'='*60}")
    
    dirs = get_target_dirs(target_name)
    cleaned_pdb = dirs["cleaned"] / "cleaned.pdb"
    
    if not cleaned_pdb.exists():
        raise FileNotFoundError(f"请先运行 pdb_cleaner.py: {cleaned_pdb}")
    
    # 识别辅因子
    print(f"  分析辅因子...")
    cofactors = parse_cofactor_info(cleaned_pdb)
    
    if cofactors:
        print(f"  发现 {len(cofactors)} 个辅因子:")
        for cf in cofactors:
            print(f"    - {cf['name']} (Chain {cf['chain']}, Res {cf['seq']}, {cf['atom_count']} atoms)")
    else:
        print(f"  未发现辅因子")
    
    # 创建 AF3 受体
    output_pdb = dirs["af3_receptor"] / "af3-receptor.pdb"
    
    cofactor_set = set(cofactor_filter) if cofactor_filter else None
    stats = create_af3_receptor(cleaned_pdb, output_pdb, keep_cofactors, cofactor_set)
    
    print(f"\n✓ AF3 受体准备完成")
    return output_pdb


def main():
    """命令行入口"""
    import argparse
    
    parser = argparse.ArgumentParser(description="准备 AlphaFold3 受体文件")
    parser.add_argument("target", help="靶点名称（如 1LYZ）")
    parser.add_argument("--no-cofactors", action="store_true", 
                       help="不保留辅因子")
    parser.add_argument("--cofactors", nargs="+", 
                       help="指定要保留的辅因子（如 ZN ATP）")
    
    args = parser.parse_args()
    
    try:
        prepare_af3_receptor(
            args.target,
            keep_cofactors=not args.no_cofactors,
            cofactor_filter=args.cofactors
        )
    except Exception as e:
        print(f"\n✗ 错误: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
